#dotnet test ./test/JornadaMilhas. Unit.Test
#dotnet test ./test/JornadaMilhas.Integration.Test.API
#dotnet publish ./src/JornadaMilhas.AΡΙ

name: Pipeline
on:
 push:
  branches: ["main"]
jobs:
  build:
   name: Minha primeira pipeline  
   runs-on: ubuntu-latest
   steps:     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 9.0.x
      - name: Checkout do código
        uses: actions/checkout@v2      
      - name: Execução do teste de unidade 
        run: dotnet test ./test/JornadaMilhas.Unit.Test
      - name: Testes Integrção 
        run: dotnet test ./test/JornadaMilhas.Integration.Test.API
      #dotnet publish ./src/JornadaMilhas.API
      - name: Publicando a API
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp ./src/JornadaMilhas.API
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AC4E48CFA71A4E93BEC74AB74A2CDB16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B5F9F583A6BB4E638F911AC535543471 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_37736E428A4B44B4AFED2E8A780D9C66 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jornadamilhas-api'
          slot-name: 'Production'
          package: .
         
  